version: '3'
services:
  db:
    container_name: local-postgres
    image: postgres:14-alpine
    environment:
      - POSTGRES_DB=group_chat_db
      - POSTGRES_USER=userlocal
      - POSTGRES_PASSWORD=letmepass
    volumes:
      - ../data:/var/lib/postgresql/data
    ports:
      - "5444:5432"

